trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: 'ubuntu-20.04'
          demands:
            - npm

        variables:
          dotnetSdkVersion: '6.x'

        steps:
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            condition: |
              and 
              (
                succeeded(),
                eq(variables['Build.SourceBranchName'], 'release')
              )

  - stage: 'Deploy'
    displayName: 'Deploy the web application'
    dependsOn: Build
    jobs:
      - deployment: Deploy
        pool:
          vmImage: 'ubuntu-20.04'
        environment: dev
        variables:
          - group: Release